-- MySQL Script generated by MySQL Workbench
-- Sáb 23 Abr 2016 11:55:02 BRT
-- Model: stb    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema std
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `std` ;

-- -----------------------------------------------------
-- Schema std
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `std` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `std` ;

-- -----------------------------------------------------
-- Table `std`.`std_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `std`.`std_login` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `perfil` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
